layout: sidebar
style: light

plugins:
   - jekyll-octicons
   - jekyll-github-metadata
   - jemoji

permalink: /:year/:month/:day/:title/

defaults:
   - scope:
        path: '' # an empty string here means all files in the project
        type: 'posts'
     values:
        layout: 'post'

projects:
   sort_by: starts
   # sort_by options:
   #   - pushed
   #   - stars
   limit: 9
   exclude:
      archived: true
      forks: true
      projects:
      # - repo-name

social_media:
   linkedin: brnpapa
   freecodecamp: brnpapa
   medium: brnpapa
   # instagram: your_username
   # behance: your_username
   # dribbble: your_username
   # facebook: your_username
   # hackerrank: your_username
   # keybase: your_username
   # mastodon: your_username
   # stackoverflow: your_user_id
   # telegram: your_username
   # twitter: your_username
   # unsplash: your_username
   # vk: your_username
   # youtube: your_username

topics:
   - name: JavaScript
     web_url: https://github.com/topics/javascript
     image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

   - name: NodeJS
     web_url: https://github.com/topics/nodejs
     image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

   - name: ReactJS
     web_url: https://github.com/topics/react
     image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

   - name: AWS
     web_url: https://github.com/topics/aws
     image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
